### ISSUE TITLE
Trashslot doesn't show

### ISSUE THREAD

**Issue by chris819t** [blay09/TrashSlot#99] opened 2022-02-21 12:00 UTC
### Minecraft Version

1.18.x

### Mod Loader

Fabric

### Mod Loader Version

Fabric 0.12.12-1.18.1

### Mod Version

trashslot-fabric-1.18-11.0.1

### Describe the Issue

The slot just doesn't simply show for me anywhere.
https://imgur.com/a/SELcAbr

### Do you use any performance-enhancing mods (e.g. OptiFine)?

sodium-fabric-mc1.18.1-0.4.0-alpha6+replaymod.rev.b90e7f3

**Comment by BlayTheNinth** [comment] 2022-02-22 20:31
There's a keybind to toggle the TrashSlot.

**Comment by chris819t** [comment] 2022-02-23 00:52
Nope. I assigned it to an unused key and I still don't see it after trying that.

**Comment by BlayTheNinth** [comment] 2022-02-23 07:41
Try deleting your `TrashSlotSaveState.json`. If it still doesn't show up, try assigning the key and toggling anyways, it could be that a mod is overriding the inventory screen in which case it will be hidden until toggled on like with any other screen.

**Comment by chris819t** [comment] 2022-03-04 01:04
I have no mod that effects the invemtory gui other than this mod. I have no TrashSlotSaveState.json file. I resassigned the keybind, and it still doesnt show

**Comment by BlayTheNinth** [comment] 2022-03-04 08:48
Does it work with only TrashSlot installed?

**Comment by SplendidAlakey** [comment] 2022-03-12 09:04
It's an incompatibility with ReplayMod. Here's the log: https://gist.github.com/SplendidAlakey/ef988eeccc3be0c1265c9f3a96e4fafb

**Comment by chris819t** [comment] 2022-03-12 10:40
Thanks for checking, ive been pretty busy lately so I havent had the chance to check

**Comment by ncottrill** [comment] 2022-05-26 16:13
Our server players are also unable to see the trashslot on occasion. Sometimes the server reboots help, sometimes they do not. We have half the players who can see the trashslot and another half who cannot. 

We do have Tinkers installed, but it is an essential mod. Is there any way the "incompatibility" can be fixed for trash slot?

**Comment by BlayTheNinth** [comment] 2022-08-16 17:05
There is no total incompatibility with Tinkers, the TrashSlot just doesn't work right when enabled for a Tinker's Construct screen. Even with Tinker's installed, it should still work just fine everywhere else.

Since this issue seems to be super sporadic and I can't reproduce it, the best bet would be trying to spot a pattern in when or to whom it happens, and gathering logs from those people at those times.

**Comment by BlayTheNinth** [comment] 2023-02-26 15:47
The issue with the ReplayMod has been fixed in the latest version for 1.18.2, 1.19.2 and 1.19.3.

**Closed as completed by BlayTheNinth** 2023-02-26 15:47 UTC
Labels: Bug
