### ISSUE TITLE
1.14.4 Client crash

### ISSUE THREAD

**Issue by Wissi** [blay09/TrashSlot#58] opened 2019-09-07 05:03 UTC
Not trying to even use the trash slot.
Client just crashed. Full crash log [here](https://gist.github.com/Wissi/42eb29753a529e634a8d20466a139993).
Probably need to be updated to newest Forge.

Using:
Forge-28.0.93
TrashSlot_1.14.4-10.4.5

**Comment by BlayTheNinth** [comment] 2019-09-07 18:47
Duplicate of #56

**Closed as completed by BlayTheNinth** 2019-09-07 18:47 UTC
Labels: Bug, Duplicate, Crash
