### ISSUE TITLE
[Suggestion] Add a list of items in the config that will be automatically trashed when picked up

### ISSUE THREAD

**Issue by leftbones** [blay09/TrashSlot#145] opened 2024-09-15 19:55 UTC
This could be done with a simple list in the config file like...
`autoTrashItems = ["minecraft:andesite", "minecraft:diorite", "minecraft:granite"]`

Or since you've already got a system in place for pressing a key while hovering over an item, you could add another key that adds or removes the item from the auto trash list.

**Comment by BlayTheNinth** [comment] 2024-09-15 20:13
Duplicate of #102, I don't believe TrashSlot is the right mod for this kind of behaviour.

**Closed as not planned by BlayTheNinth** 2024-09-15 20:13 UTC
Labels: Feature, Duplicate

**Comment by emihead** [comment] 2024-09-23 13:07
I'm a bit late, but maybe it'd work a bit better if it worked like Terraria's [Auto Trash mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2565540604), adding an additional slot next to the ordinary trash slot which lets the user quickly add items to their auto trash list rather than having to mess around with config. Maybe this would be better as its own issue, but I figured I should bring it up here
I've wanted a Minecraft version of the aforementioned mod for a while and I feel like integrating it with TrashSlot is the most obvious choice, whether in an update or an official/unofficial addon. If it doesn't get added to the mod in any official capacity, I still hope someone tackles the idea someday... It'd be a savior for mining trips
