### ISSUE TITLE
1.14.4 Client Crash.

### ISSUE THREAD

**Issue by Wissi** [blay09/TrashSlot#60] opened 2019-09-12 06:16 UTC
Getting this error in crash report:    (full crash log [here](https://gist.github.com/Wissi/895ed2c98a09a1ae11684ef55826ee33).)
```
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at net.blay09.mods.trashslot.TrashHelper.getTrashItem(TrashHelper.java:19) ~[?:10.4.5] {}
	at net.blay09.mods.trashslot.TrashSlot.onPlayerOpenContainer(TrashSlot.java:89) ~[?:10.4.5] {}
```
Forge-28.0.104
TrashSlot_1.14.4-10.4.5

Happened while right clicking on an Farmer Villager to see it's trades.

**Comment by BlayTheNinth** [comment] 2019-09-12 14:52
Duplicate of #58 and TrashSlot 10.4.6 has since been released to fix the issue.

**Closed as completed by BlayTheNinth** 2019-09-12 14:52 UTC
Labels: Bug, Duplicate, Crash
