### ISSUE TITLE
trash slot crash when opening crafting table

### ISSUE THREAD

**Issue by colemy** [blay09/TrashSlot#59] opened 2019-09-07 18:35 UTC
as title says, trash slot version 10.4.5 and forge version 28.0.93

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/7/19 1:32 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getEntityData()Lnet/minecraft/nbt/CompoundNBT;
	at net.blay09.mods.trashslot.TrashHelper.getTrashItem(TrashHelper.java:19) ~[?:10.4.5] {}
	at net.blay09.mods.trashslot.TrashSlot.onPlayerOpenContainer(TrashSlot.java:89) ~[?:10.4.5] {}
	at net.minecraftforge.eventbus.ASMEventHandler_162_TrashSlot_onPlayerOpenContainer_Open.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:182) ~[?:?] {}
	at net.minecraftforge.fml.network.NetworkHooks.openGui(NetworkHooks.java:141) ~[?:?] {}
	at com.tfar.craftingstation.CraftingStationBlock.func_220051_a(CraftingStationBlock.java:56) ~[?:2.0.2a] {}
	at net.minecraft.block.BlockState.func_215687_a(BlockState.java:395) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:322) ~[?:?] {}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:847) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:33) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:170) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:135) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:148) ~[?:?] {pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3319950784 bytes (3166 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.93.jar runtimedistcleaner PLUGINSERVICE 
		/optifine-f4-pre4-mod.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.93.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.93
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		AmbientSounds-3.0.9.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		AppleSkin-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 DONE}
		BetterSprinting-v3.0.1a.jar Better Sprinting {bettersprinting@3.0.1a DONE}
		BetterTitleScreen-1.14.4-1.7.jar Better Title Screen {bettertitlescreen@1.14.4-1.7 DONE}
		biomeinfo-1.14.4-v1.2.4.jar BiomeInfo {biomeinfo@v1.2.4 DONE}
		BiomesOPlenty-1.14.4-9.0.0.252-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.252 DONE}
		caelus-FORGE-1.14.4-0.11.jar Caelus API {caelus@FORGE-1.14.4-0.11 DONE}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 DONE}
		Controlling-5.0.3.jar Controlling {controlling@5.0.3 DONE}
		Craftable+Saddles+[1.14]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		craftingstation-2.0.2a.jar Crafting Station {craftingstation@2.0.2a DONE}
		curios-FORGE-1.14.4-0.24.jar Curios API {curios@FORGE-1.14.4-0.24 DONE}
		curiouselytra-FORGE-1.14.4-0.7.jar Curious Elytra {curiouselytra@FORGE-1.14.4-0.7 DONE}
		DefaultOptions-10.2.6.jar Default Options {defaultoptions@10.2.6 DONE}
		dragon-drops-elytra-1.14.4-1.0.jar Dragon Drops Elytra {dde@1.0 DONE}
		dwmh-1.14.4-3.0.1.jar Dude! Where's my Horse? {dwmh@1.14.4-3.0.1 DONE}
		elevator-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 DONE}
		extcaves-1.1.jar Extended Caves {extcaves@1.1 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		FleshToLeather-1.14.3-1.1.0.jar FleshToLeather {fleshtoleather@1.1.0 DONE}
		furniture-7.0.0-pre5.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 DONE}
		GamemodeOverhaul-1.14.4-1.4.2.1.jar GamemodeOverhaul {gamemodeoverhaul@1.14.4-1.4.2.1 DONE}
		Harvest-forge-1.2.10-23.jar Harvest {harvest@version DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 DONE}
		ironchest-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		KleeSlabs-7.4.7.jar KleeSlabs {kleeslabs@7.4.7 DONE}
		lampblock-branders-v1.1.1-1.14.4.jar Lamp Block Mod {lampblockmod@1.1.1 DONE}
		LightOverlay-3.4.jar Light Overlay Forge {lightoverlay-forge@3.4 DONE}
		metalbarrels-1.3c.jar Metal Barrels {metalbarrels@1.3c DONE}
		mining_dimension-1.14.4-1.0.2.jar Mining World {mining_dimension@1.14.4-1.0.2 DONE}
		Morpheus-1.14.4-4.2.38.jar Morpheus {morpheus@version DONE}
		nat-charged-creepers-1.1.jar Naturally Charged Creepers {ncc@1.1 DONE}
		Ping-1.6.3.jar Ping {ping@1.14.4-1.6.3 DONE}
		Placebo-1.14.4-2.2.0.jar Placebo {placebo@2.2.0 DONE}
		practicaltools-1.4.jar Practical Tools {practicaltools@1.14.4-1.4 DONE}
		reap-1.10.1.jar Reap Mod {reap@1.10.1 DONE}
		ring-of-angel-1.0.1.jar Angel Ring {angelring@1.0.1 DONE}
		RingOfAttraction-1.14.4-1.0.10.jar Ring of Attraction {ring_of_attraction@1.0.10 DONE}
		RingOfBlink-1.14.4-1.0.13.jar Ring of Blink {ring_of_blink@1.0.13 DONE}
		RingOfEnderchest-1.14.4-1.0.10.jar Ring of Enderchest {ring_of_enderchest@1.0.10 DONE}
		RingOfMiner-1.14.4-1.0.8.jar Ring of Miner {ring_of_miner@1.0.8 DONE}
		RingOfRepair-1.14.4-1.0.11.jar Ring of Repair {ring_of_repair@1.0.11 DONE}
		ScreenshotToClipboard-1.14.3-1.0.2.jar Screenshot to Clipboard {screenshotclipboard@1.14.3-1.0.2 DONE}
		searchablechests-1.5.1.jar Searchable Chests {searchablechests@1.5.1 DONE}
		SimpleDivingGear-3.0.1.jar Simple Diving Gear {simpledivegear@3.0.1 mc 1.14.4 DONE}
		smooth-scrolling-everywhere-1.1.jar Smooth Scrolling Everywhere {smooth-scrolling-everywhere@1.1 DONE}
		spiketraps-1.0.jar Spike Traps {spiketraps@1.0 DONE}
		strongfarmland-1.14.4-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.14.4-1.0.0 DONE}
		sulfur-potassium-branders-2.2.2-1.14.4.jar Sulfur And Potassium - make gunpowder {sulfurpotassiummod@2.2.2 DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		ToastControl-1.14.4-2.2.0.jar Toast Control {toastcontrol@2.2.0 DONE}
		tombstone-4.1.1-1.14.4.jar Corail Tombstone {tombstone@4.1.1 DONE}
		tramplestopper-2.0.0.22.jar Trample Stopper {tramplestopper@1.14.4-2.0.0.22-universal DONE}
		TrashSlot-10.4.5.jar TrashSlot {trashslot@10.4.5 DONE}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		useful_backpacks-u-team-core-1.14.4-2.5.5.120.jar U Team Core {uteamcore@2.5.5.120 DONE}
		voxel-map-1.9.13b.jar VoxelMap {voxelmap@1.9.13 DONE}
		Waddles-0.8.3.jar Waddles {waddles@1.14.4-0.8.3 DONE}
		well-fed-branders-1.14.4-1.2.0.jar Well Fed - quality food! {wellfedmod@1.2.0 DONE}
		worldedit-forge-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
		forge-1.14.4-28.0.93-universal.jar Forge {forge@28.0.93 DONE}
		forge-1.14.4-28.0.93-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['cpm9'/173, l='127 testt', x=62.15, y=69.00, z=-100.27]]
	Data Packs: vanilla, mod:worldedit, mod:wellfedmod, mod:waila, mod:waddles, mod:voxelmap, mod:uteamcore, mod:usefulbackpacks, mod:trashslot, mod:tramplestopper, mod:tombstone, mod:toastcontrol, mod:swingthroughgrass, mod:sulfurpotassiummod, mod:strongfarmland, mod:spiketraps, mod:smooth-scrolling-everywhere, mod:simpledivegear, mod:searchablechests, mod:screenshotclipboard, mod:ring_of_repair, mod:ring_of_miner, mod:ring_of_enderchest, mod:ring_of_blink, mod:ring_of_attraction, mod:reap, mod:practicaltools, mod:placebo, mod:ping, mod:ncc, mod:morpheus, mod:mining_dimension, mod:metalbarrels, mod:lightoverlay-forge, mod:lampblockmod, mod:kleeslabs, mod:jei, mod:ironchest, mod:inventorysorter, mod:harvest, mod:gamemodeoverhaul, mod:forge, mod:fleshtoleather, mod:fastleafdecay, mod:extcaves, mod:elevatorid, mod:dwmh, mod:defaultoptions, mod:dde, mod:curiouselytra, mod:curios, mod:craftingstation, mod:craftable_saddles, mod:controlling, mod:clumps, mod:cfm, mod:caelus, mod:biomesoplenty, mod:biomeinfo, mod:bettertitlescreen, mod:bettersprinting, mod:appleskin, mod:angelring, mod:ambientsounds
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by BlayTheNinth** [comment] 2019-09-07 18:48
Duplicate of #56

**Closed as completed by BlayTheNinth** 2019-09-07 18:48 UTC
Labels: Bug, Duplicate, Crash
